# Generated by Django 4.2 on 2023-10-24 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devicedata', '0002_device_extra_time_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='evening_shift_start_time',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AddField(
            model_name='company',
            name='morning_shift_start_time',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
